import Error from 'next/error'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

// http://localhost:3000/g/1/2/dataA;z?dataB=z#&dataC=z

// { entity: 'apple-touch-icon-precomposed.png' } /apple-touch-icon-precomposed.png
// { entity: 'apple-touch-icon.png' } /apple-touch-icon.png

type Props = {
  entity: string
  url: string
  data?: string
}

export async function getServerSideProps(context: any) {
  const { params, req } = context

  const entity = params.entity
  const data = params.slug[params.slug.length - 1]
  const url = `https://${req.headers.host}${req.url}`

  return { props: { entity, data, url } }
}

export default function Entity(props: Props) {
  const [location, setLocation] = useState<Location>()

  useEffect(() => {
    setLocation(window.location)
  }, [])

  const { entity, data, url } = props

  if (!['c', 'cc', 'u'].includes(entity)) {
    return <Error statusCode={404} />
  }

  const searchParams = new URL(url).searchParams.toString()

  return (
    <>
      <Head>
        <title>Status</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content={`${
            process.env.VERCEL_URL ? 'https://' + process.env.VERCEL_URL : ''
          }/api/og?${searchParams}`}
        />
      </Head>
      <main className={styles.main}>
        <div>
          <p className={inter.className}>{JSON.stringify(url)}</p>
        </div>

        {location && (
          <div>
            <p className={inter.className}>{location.href}</p>
          </div>
        )}
      </main>
    </>
  )
}
